// import { Geist, Geist_Mono } from "next/font/google";
import {Poppins} from "next/font/google"
import "./globals.css";
import Header from "./Component/Header";
import Footer from "./Component/Footer";

const font= Poppins({
  weight:['100', '200', '300','400','500','600'],
  subsets:["latin"],
})
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Tour & Travel Next App",
  description: "Generated by  Tour & Travel app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className}  antialiased`}
      ><Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
